[theme]
primaryColor = "#ADD8E6"                # light blue em Hex
backgroundColor = "#5FCCEB"             #rgb(95, 204, 235) convertido para Hex
secondaryBackgroundColor = "#0000FF"    
textColor = "#160303"                   
font = "sans serif"                     # Aspas fechadas corretamente