[theme]
primaryColor = "#606060"                # Cinza Médio (Destaques)
backgroundColor = "#FAFAFA"             # Off-White (Quase branco)
secondaryBackgroundColor = "#E5E5E5"    # Cinza claro (Sidebar)
textColor = "#262730"                   # Preto carvão (Texto)
font = "sans serif"